'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Unmanaged.Net_Converter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #include &lt;stdio.h&gt;
        '''#include &lt;Windows.h&gt;
        '''
        '''typedef void(*DllMainEx)();
        '''
        '''unsigned char rawData[$DataLength$] = {
        '''	$DataByte$
        '''};
        '''
        '''
        '''int main()
        '''{
        '''
        '''	char *Pathvar = getenv(&quot;TEMP&quot;);
        '''	char *DLLName = &quot;$DllName$&quot;;
        '''	char *EntryPoint = &quot;$DllMain$&quot;;
        '''
        '''	if (Pathvar != &quot;&quot;) {
        '''       DLLName = strcat(Pathvar, DLLName);
        '''	}
        '''
        '''	remove(DLLName);
        '''
        '''	printf(&quot;Writing dll\n&quot;);
        '''
        '''	FILE *fp = fopen(DLLName, &quot;wb&quot;);
        '''   
        '''	if (fp) {
        '''		fwrite(rawData, 1, sizeof(rawData), fp);
        '''		fclose(fp);
        '''	}
        '''
        '''	printf(&quot;Loading  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BaseLinker() As String
            Get
                Return ResourceManager.GetString("BaseLinker", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
